name: "Version Pack"
description: "Generates a version number from github.ref.version-pack"
author: "Nivaes"
inputs:
  prerelease:
    description: "Prerelease identifier"
    required: false
  version:
    description: "Version number"
    required: false   
outputs:
  version-number:
    description: "Version number"
    value: ${{ steps.run.outputs.version-number }}
  version-pack:
    description: "Version pack"
    value: ${{ steps.run.outputs.version-pack }}
  version-release:
    description: "Version release"
    value: ${{ steps.run.outputs.version-release }}
runs:
  using: "composite"
  steps:
    - name: Install dotnet-script
      shell: bash
      run: dotnet tool install -g dotnet-script

    - name: New version
      id: run
      shell: bash
      run: |
        git ls-remote --tags origin '{versionMajor}.*'
        
        output=$(~/.dotnet/tools/dotnet-script $GITHUB_ACTION_PATH/src/Run.csx -- --prerelease="${{ inputs.prerelease }}" --version="${{ inputs.version }}")

        version_number=$(echo "$output" | tail -n 3 | sed -n '1p')
        version_pack=$(echo "$output" | tail -n 3 | sed -n '2p')
        version_release=$(echo "$output" | tail -n 3 | sed -n '3p')

        echo number: $version_number pack: $version_pack release: $version_release

        echo "version-number=$version_number" >> $GITHUB_OUTPUT
        echo "version-pack=$version_pack" >> $GITHUB_OUTPUT
        echo "version-release=$version_release" >> $GITHUB_OUTPUT

branding:
  icon: "tag"
  color: "gray-dark"
