name: "Version Pack"
description: "Generates a version number from github.ref.version-pack"
author: "Nivaes"
inputs:
  package-flow:
    description: "Generate the package flow version."
    required: false
outputs:
  version:
    description: "The generate version pack"
    value: ${{ steps.run.outputs.version }}
  major:
    description: "Version major"
    value: ${{ steps.run.outputs.major }}
  minor:
    description: "Version major"
    value: ${{ steps.run.outputs.minor }}
runs:
  using: "composite"
  steps:
    - name: Instalar dotnet-script
      shell: bash
      run: dotnet tool install -g dotnet-script

    - name: Ejecutar script C#
      id: run
      shell: bash
      run: |
        output=$(~/.dotnet/tools/dotnet-script $GITHUB_ACTION_PATH/src/Run.csx ${{ inputs.package-flow }})
        
        version=$(echo "$output" | tail -n 3 | sed -n '1p')
        major=$(echo "$output" | tail -n 3 | sed -n '2p')
        minor=$(echo "$output" | tail -n 3 | sed -n '3p')

        echo Version: $version

        echo "version=$version" >> $GITHUB_OUTPUT
        echo "major=$major" >> $GITHUB_OUTPUT
        echo "minor=$minor" >> $GITHUB_OUTPUT
branding:
  icon: "tag"
  color: "gray-dark"
