name: "Version Pack"
description: "Generates a version number from github.ref.version-pack"
author: "Nivaes"
inputs:
  package-flow:
    description: "Generate the package flow version."
    required: false
outputs:
  version-pack:
    description: "Version pack"
    value: ${{ steps.run.outputs.version-pack }}
  version-release:
    description: "Version release"
    value: ${{ steps.run.outputs.version-release }}
runs:
  using: "composite"
  steps:
    - name: Instalar dotnet-script
      shell: bash
      run: dotnet tool install -g dotnet-script

    - name: Ejecutar script C#
      id: run
      shell: bash
      run: |
        output=$(~/.dotnet/tools/dotnet-script $GITHUB_ACTION_PATH/src/Run.csx ${{ inputs.package-flow }})
        
        version-pack=$(echo "$output" | tail -n 3 | sed -n '1p')
        version-release=$(echo "$output" | tail -n 3 | sed -n '2p')

        echo Version: $version-release - $version-pack

        echo "version-pack=$version-pack" >> $GITHUB_OUTPUT
        echo "version-release=$version-release" >> $GITHUB_OUTPUT
branding:
  icon: "tag"
  color: "gray-dark"
